### ISSUE TITLE
The About page links that are in dark sections are hard to see

### ISSUE THREAD

**Issue by jaytula** [chingu-voyages/moonshot-chingu-quiz#161]
For example http://localhost:3000/about:

![image](https://user-images.githubusercontent.com/75389/115316834-08511b00-a12f-11eb-804d-855d7169f29a.png)

Maybe add some styles for links to `Text` export in `./components/aboutUs/style.ts`:

```css
a:link, a:visited {
  color: white;
  text-decoration: underline;
}
```
